//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mobile.Droid.intranet.itg.cms_ws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultasSoap", Namespace="http://tempuri.org/")]
    public partial class Consultas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaConsolidadaValoresPagarOperationCompleted;
        
        private System.Threading.SendOrPostCallback RelatorioComissaoPagarDetalhePDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDetalheMovimentoPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDominiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCNPJporNumSusepOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlertaPagamentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarcarAlertaPagamentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RelatorioDemonstrativoComissaoPagoPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaConsolidadaPagamentoPorDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDemonstrativoPagoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Consultas() {
            Url = "http://200.152.194.6:8888/consultas.asmx";
            if ((IsLocalFileSystemWebService(Url) == true)) {
                UseDefaultCredentials = true;
                useDefaultCredentialsSetExplicitly = false;
            }
            else {
                useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((IsLocalFileSystemWebService(base.Url) == true) 
                            && (useDefaultCredentialsSetExplicitly == false)) 
                            && (IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaConsolidadaValoresPagarCompletedEventHandler ConsultaConsolidadaValoresPagarCompleted;
        
        /// <remarks/>
        public event RelatorioComissaoPagarDetalhePDFCompletedEventHandler RelatorioComissaoPagarDetalhePDFCompleted;
        
        /// <remarks/>
        public event ConsultaDetalheMovimentoPagoCompletedEventHandler ConsultaDetalheMovimentoPagoCompleted;
        
        /// <remarks/>
        public event ConsultaDominiosCompletedEventHandler ConsultaDominiosCompleted;
        
        /// <remarks/>
        public event ConsultaCNPJporNumSusepCompletedEventHandler ConsultaCNPJporNumSusepCompleted;
        
        /// <remarks/>
        public event AlertaPagamentosCompletedEventHandler AlertaPagamentosCompleted;
        
        /// <remarks/>
        public event MarcarAlertaPagamentosCompletedEventHandler MarcarAlertaPagamentosCompleted;
        
        /// <remarks/>
        public event RelatorioDemonstrativoComissaoPagoPDFCompletedEventHandler RelatorioDemonstrativoComissaoPagoPDFCompleted;
        
        /// <remarks/>
        public event ConsultaConsolidadaPagamentoPorDataCompletedEventHandler ConsultaConsolidadaPagamentoPorDataCompleted;
        
        /// <remarks/>
        public event ConsultaDemonstrativoPagoCompletedEventHandler ConsultaDemonstrativoPagoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaConsolidadaValoresPagar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaConsolidadaValoresPagar(string Parametros) {
            object[] results = Invoke("ConsultaConsolidadaValoresPagar", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaConsolidadaValoresPagarAsync(string Parametros) {
            ConsultaConsolidadaValoresPagarAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void ConsultaConsolidadaValoresPagarAsync(string Parametros, object userState) {
            if ((ConsultaConsolidadaValoresPagarOperationCompleted == null)) {
                ConsultaConsolidadaValoresPagarOperationCompleted = new System.Threading.SendOrPostCallback(OnConsultaConsolidadaValoresPagarOperationCompleted);
            }
            InvokeAsync("ConsultaConsolidadaValoresPagar", new object[] {
                        Parametros}, ConsultaConsolidadaValoresPagarOperationCompleted, userState);
        }
        
        private void OnConsultaConsolidadaValoresPagarOperationCompleted(object arg) {
            if ((ConsultaConsolidadaValoresPagarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                ConsultaConsolidadaValoresPagarCompleted(this, new ConsultaConsolidadaValoresPagarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RelatorioComissaoPagarDetalhePDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RelatorioComissaoPagarDetalhePDF(string Parametros) {
            object[] results = Invoke("RelatorioComissaoPagarDetalhePDF", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RelatorioComissaoPagarDetalhePDFAsync(string Parametros) {
            RelatorioComissaoPagarDetalhePDFAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void RelatorioComissaoPagarDetalhePDFAsync(string Parametros, object userState) {
            if ((RelatorioComissaoPagarDetalhePDFOperationCompleted == null)) {
                RelatorioComissaoPagarDetalhePDFOperationCompleted = new System.Threading.SendOrPostCallback(OnRelatorioComissaoPagarDetalhePDFOperationCompleted);
            }
            InvokeAsync("RelatorioComissaoPagarDetalhePDF", new object[] {
                        Parametros}, RelatorioComissaoPagarDetalhePDFOperationCompleted, userState);
        }
        
        private void OnRelatorioComissaoPagarDetalhePDFOperationCompleted(object arg) {
            if ((RelatorioComissaoPagarDetalhePDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                RelatorioComissaoPagarDetalhePDFCompleted(this, new RelatorioComissaoPagarDetalhePDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDetalheMovimentoPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaDetalheMovimentoPago(string Parametros) {
            object[] results = Invoke("ConsultaDetalheMovimentoPago", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDetalheMovimentoPagoAsync(string Parametros) {
            ConsultaDetalheMovimentoPagoAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void ConsultaDetalheMovimentoPagoAsync(string Parametros, object userState) {
            if ((ConsultaDetalheMovimentoPagoOperationCompleted == null)) {
                ConsultaDetalheMovimentoPagoOperationCompleted = new System.Threading.SendOrPostCallback(OnConsultaDetalheMovimentoPagoOperationCompleted);
            }
            InvokeAsync("ConsultaDetalheMovimentoPago", new object[] {
                        Parametros}, ConsultaDetalheMovimentoPagoOperationCompleted, userState);
        }
        
        private void OnConsultaDetalheMovimentoPagoOperationCompleted(object arg) {
            if ((ConsultaDetalheMovimentoPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                ConsultaDetalheMovimentoPagoCompleted(this, new ConsultaDetalheMovimentoPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDominios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaDominios() {
            object[] results = Invoke("ConsultaDominios", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDominiosAsync() {
            ConsultaDominiosAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaDominiosAsync(object userState) {
            if ((ConsultaDominiosOperationCompleted == null)) {
                ConsultaDominiosOperationCompleted = new System.Threading.SendOrPostCallback(OnConsultaDominiosOperationCompleted);
            }
            InvokeAsync("ConsultaDominios", new object[0], ConsultaDominiosOperationCompleted, userState);
        }
        
        private void OnConsultaDominiosOperationCompleted(object arg) {
            if ((ConsultaDominiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                ConsultaDominiosCompleted(this, new ConsultaDominiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaCNPJporNumSusep", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaCNPJporNumSusep(string Parametros) {
            object[] results = Invoke("ConsultaCNPJporNumSusep", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCNPJporNumSusepAsync(string Parametros) {
            ConsultaCNPJporNumSusepAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void ConsultaCNPJporNumSusepAsync(string Parametros, object userState) {
            if ((ConsultaCNPJporNumSusepOperationCompleted == null)) {
                ConsultaCNPJporNumSusepOperationCompleted = new System.Threading.SendOrPostCallback(OnConsultaCNPJporNumSusepOperationCompleted);
            }
            InvokeAsync("ConsultaCNPJporNumSusep", new object[] {
                        Parametros}, ConsultaCNPJporNumSusepOperationCompleted, userState);
        }
        
        private void OnConsultaCNPJporNumSusepOperationCompleted(object arg) {
            if ((ConsultaCNPJporNumSusepCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                ConsultaCNPJporNumSusepCompleted(this, new ConsultaCNPJporNumSusepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlertaPagamentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AlertaPagamentos() {
            object[] results = Invoke("AlertaPagamentos", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AlertaPagamentosAsync() {
            AlertaPagamentosAsync(null);
        }
        
        /// <remarks/>
        public void AlertaPagamentosAsync(object userState) {
            if ((AlertaPagamentosOperationCompleted == null)) {
                AlertaPagamentosOperationCompleted = new System.Threading.SendOrPostCallback(OnAlertaPagamentosOperationCompleted);
            }
            InvokeAsync("AlertaPagamentos", new object[0], AlertaPagamentosOperationCompleted, userState);
        }
        
        private void OnAlertaPagamentosOperationCompleted(object arg) {
            if ((AlertaPagamentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                AlertaPagamentosCompleted(this, new AlertaPagamentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarcarAlertaPagamentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MarcarAlertaPagamentos(string Parametros) {
            object[] results = Invoke("MarcarAlertaPagamentos", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MarcarAlertaPagamentosAsync(string Parametros) {
            MarcarAlertaPagamentosAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void MarcarAlertaPagamentosAsync(string Parametros, object userState) {
            if ((MarcarAlertaPagamentosOperationCompleted == null)) {
                MarcarAlertaPagamentosOperationCompleted = new System.Threading.SendOrPostCallback(OnMarcarAlertaPagamentosOperationCompleted);
            }
            InvokeAsync("MarcarAlertaPagamentos", new object[] {
                        Parametros}, MarcarAlertaPagamentosOperationCompleted, userState);
        }
        
        private void OnMarcarAlertaPagamentosOperationCompleted(object arg) {
            if ((MarcarAlertaPagamentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                MarcarAlertaPagamentosCompleted(this, new MarcarAlertaPagamentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RelatorioDemonstrativoComissaoPagoPDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RelatorioDemonstrativoComissaoPagoPDF(string Parametros) {
            object[] results = Invoke("RelatorioDemonstrativoComissaoPagoPDF", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RelatorioDemonstrativoComissaoPagoPDFAsync(string Parametros) {
            RelatorioDemonstrativoComissaoPagoPDFAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void RelatorioDemonstrativoComissaoPagoPDFAsync(string Parametros, object userState) {
            if ((RelatorioDemonstrativoComissaoPagoPDFOperationCompleted == null)) {
                RelatorioDemonstrativoComissaoPagoPDFOperationCompleted = new System.Threading.SendOrPostCallback(OnRelatorioDemonstrativoComissaoPagoPDFOperationCompleted);
            }
            InvokeAsync("RelatorioDemonstrativoComissaoPagoPDF", new object[] {
                        Parametros}, RelatorioDemonstrativoComissaoPagoPDFOperationCompleted, userState);
        }
        
        private void OnRelatorioDemonstrativoComissaoPagoPDFOperationCompleted(object arg) {
            if ((RelatorioDemonstrativoComissaoPagoPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                RelatorioDemonstrativoComissaoPagoPDFCompleted(this, new RelatorioDemonstrativoComissaoPagoPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaConsolidadaPagamentoPorData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaConsolidadaPagamentoPorData(string Parametros) {
            object[] results = Invoke("ConsultaConsolidadaPagamentoPorData", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaConsolidadaPagamentoPorDataAsync(string Parametros) {
            ConsultaConsolidadaPagamentoPorDataAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void ConsultaConsolidadaPagamentoPorDataAsync(string Parametros, object userState) {
            if ((ConsultaConsolidadaPagamentoPorDataOperationCompleted == null)) {
                ConsultaConsolidadaPagamentoPorDataOperationCompleted = new System.Threading.SendOrPostCallback(OnConsultaConsolidadaPagamentoPorDataOperationCompleted);
            }
            InvokeAsync("ConsultaConsolidadaPagamentoPorData", new object[] {
                        Parametros}, ConsultaConsolidadaPagamentoPorDataOperationCompleted, userState);
        }
        
        private void OnConsultaConsolidadaPagamentoPorDataOperationCompleted(object arg) {
            if ((ConsultaConsolidadaPagamentoPorDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                ConsultaConsolidadaPagamentoPorDataCompleted(this, new ConsultaConsolidadaPagamentoPorDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDemonstrativoPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaDemonstrativoPago(string Parametros) {
            object[] results = Invoke("ConsultaDemonstrativoPago", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDemonstrativoPagoAsync(string Parametros) {
            ConsultaDemonstrativoPagoAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void ConsultaDemonstrativoPagoAsync(string Parametros, object userState) {
            if ((ConsultaDemonstrativoPagoOperationCompleted == null)) {
                ConsultaDemonstrativoPagoOperationCompleted = new System.Threading.SendOrPostCallback(OnConsultaDemonstrativoPagoOperationCompleted);
            }
            InvokeAsync("ConsultaDemonstrativoPago", new object[] {
                        Parametros}, ConsultaDemonstrativoPagoOperationCompleted, userState);
        }
        
        private void OnConsultaDemonstrativoPagoOperationCompleted(object arg) {
            if ((ConsultaDemonstrativoPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                ConsultaDemonstrativoPagoCompleted(this, new ConsultaDemonstrativoPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaConsolidadaValoresPagarCompletedEventHandler(object sender, ConsultaConsolidadaValoresPagarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaConsolidadaValoresPagarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaConsolidadaValoresPagarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RelatorioComissaoPagarDetalhePDFCompletedEventHandler(object sender, RelatorioComissaoPagarDetalhePDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RelatorioComissaoPagarDetalhePDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RelatorioComissaoPagarDetalhePDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaDetalheMovimentoPagoCompletedEventHandler(object sender, ConsultaDetalheMovimentoPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDetalheMovimentoPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDetalheMovimentoPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaDominiosCompletedEventHandler(object sender, ConsultaDominiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDominiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDominiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaCNPJporNumSusepCompletedEventHandler(object sender, ConsultaCNPJporNumSusepCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCNPJporNumSusepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCNPJporNumSusepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AlertaPagamentosCompletedEventHandler(object sender, AlertaPagamentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlertaPagamentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlertaPagamentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MarcarAlertaPagamentosCompletedEventHandler(object sender, MarcarAlertaPagamentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarcarAlertaPagamentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarcarAlertaPagamentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RelatorioDemonstrativoComissaoPagoPDFCompletedEventHandler(object sender, RelatorioDemonstrativoComissaoPagoPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RelatorioDemonstrativoComissaoPagoPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RelatorioDemonstrativoComissaoPagoPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaConsolidadaPagamentoPorDataCompletedEventHandler(object sender, ConsultaConsolidadaPagamentoPorDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaConsolidadaPagamentoPorDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaConsolidadaPagamentoPorDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaDemonstrativoPagoCompletedEventHandler(object sender, ConsultaDemonstrativoPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDemonstrativoPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDemonstrativoPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                RaiseExceptionIfNecessary();
                return ((string)(results[0]));
            }
        }
    }
}

#pragma warning restore 1591