//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Resource {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MobileResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobileResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Resource.MobileResource", typeof(MobileResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--8.1 Consolidada de pagamento por data--&gt;
        ///&lt;!--Exemplo de entrada--&gt;
        ///&lt;!--Metodo: ConsultaConsolidadaPagamentoPorData (ref 8.1)--&gt;
        ///&lt;!--Campo comentado refere-se aos campos de consulta da ITG--&gt;
        ///&lt;EntradaComissoes xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Parametros xsi:type=&quot;ParametroListaComissaoPagas&quot;&gt;
        ///    &lt;!--DataInicial--&gt;
        ///    &lt;dataInicial&gt;@dtInicial&lt;/dataInicial&gt;
        ///    &lt;!--DataFinal--&gt;
        ///    &lt;dataFinal&gt;@dtFinal&lt;/dataFinal&gt;
        ///    &lt;nr_pagina&gt;1&lt;/nr_pagina&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_8_1 {
            get {
                return ResourceManager.GetString("input_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--8.4 Demonstrativo de comissao paga em PDF--&gt;
        ///&lt;!--Exemplo de entrada--&gt;
        ///&lt;!--Metodo: RelatorioDemonstrativoComissaoPagoPDF (ref 8.4)--&gt;
        ///&lt;!--Campo comentado refere-se aos campos de consulta da ITG--&gt;
        ///&lt;EntradaComissoes xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Parametros xsi:type=&quot;ParametroDemostrativoComissoesPagas&quot;&gt;
        ///    &lt;!--DataInicial--&gt;
        ///    &lt;dataInicial&gt;@dtInicial&lt;/dataInicial&gt;
        ///    &lt;!--DataFinal--&gt;
        ///    &lt;dataFinal&gt;@dtFinal&lt;/dataFinal&gt;
        ///    &lt;cnpjs&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_8_4 {
            get {
                return ResourceManager.GetString("input_8_4", resourceCulture);
            }
        }
    }
}
